name: CD Pipeline (Deploy)

on:
  push:
    branches:
      - main

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "BRIGE Help Bot"

    steps:
      - name: Deploy to Ubuntu Server via SSH
        uses: appleboy/ssh-action@029f5b4aeeeb58fdfe1410a5d17f967dacf36262 # v1.0.3
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: ${{ vars.GEMINI_MODEL }}
          ADSGRAM_BLOCK_ID: ${{ vars.ADSGRAM_BLOCK_ID }}
          BASE_URL: ${{ vars.BASE_URL }}
          PORT: ${{ vars.PORT }}
          ADSGRAM_SECRET: ${{ secrets.ADSGRAM_SECRET }}
          ADSGRAM_API_TOKEN: ${{ secrets.ADSGRAM_API_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          envs: TELEGRAM_TOKEN,GEMINI_API_KEY,GEMINI_MODEL,ADSGRAM_BLOCK_ID,BASE_URL,PORT,ADSGRAM_SECRET,ADSGRAM_API_TOKEN
          script: |
            cd ${{ secrets.WORK_DIR }}
            git fetch origin main
            git reset --hard origin/main
            
            # Generate .env file dynamically
            echo "TELEGRAM_TOKEN=\"$TELEGRAM_TOKEN\"" > .env
            echo "GEMINI_API_KEY=\"$GEMINI_API_KEY\"" >> .env
            echo "GEMINI_MODEL=$GEMINI_MODEL" >> .env
            
            if [ -n "$ADSGRAM_BLOCK_ID" ]; then
              echo "ADSGRAM_BLOCK_ID=\"$ADSGRAM_BLOCK_ID\"" >> .env
            fi
            if [ -n "$BASE_URL" ]; then
              echo "BASE_URL=\"$BASE_URL\"" >> .env
            fi
            if [ -n "$PORT" ]; then
              echo "PORT=$PORT" >> .env
            fi
            if [ -n "$ADSGRAM_SECRET" ]; then
              echo "ADSGRAM_SECRET=\"$ADSGRAM_SECRET\"" >> .env
            fi
            if [ -n "$ADSGRAM_API_TOKEN" ]; then
              echo "ADSGRAM_API_TOKEN=\"$ADSGRAM_API_TOKEN\"" >> .env
            fi

            
            # Restrict permissions for security
            chmod 600 .env
            
            make deploy

